import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Toaster } from 'react-hot-toast';
import AuthProvider from '@/components/AuthProvider'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import Navbar from "@/components/Navbar";

async function getSession() {
  const session = await getServerSession(authOptions)
  return session
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession()

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.0/css/all.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-right"
          reverseOrder={false}
        />
        
        <AuthProvider session={session}>
          <Navbar />
          <div className="min-h-screen bg-gray-100 py-6">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
